package facema.view;

//import facema.controller.AlunoController;
import facema.dao.AlunoDao;
import javax.swing.JFrame;

/**
 *
 * @author savio
 */
public class TelaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form TelaCadastroUser
     */
    public TelaPrincipal() {
        initComponents();
        AlunoDao aluno = new AlunoDao();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnNomeAluno = new javax.swing.JButton();
        btnListarAluno = new javax.swing.JButton();
        btnCadastrarAluno = new javax.swing.JButton();
        desktopTela = new javax.swing.JDesktopPane();
        btnDeletar = new javax.swing.JButton();
        btnAlterarAluno = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Controle de Alunos");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setExtendedState(1);
        setPreferredSize(new java.awt.Dimension(1366, 728));
        setResizable(false);

        btnNomeAluno.setText("Pesquisar Aluno");
        btnNomeAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNomeAlunoActionPerformed(evt);
            }
        });

        btnListarAluno.setText("Listar Alunos");
        btnListarAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListarAlunoActionPerformed(evt);
            }
        });

        btnCadastrarAluno.setText("Cadastrar Aluno");
        btnCadastrarAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarAlunoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout desktopTelaLayout = new javax.swing.GroupLayout(desktopTela);
        desktopTela.setLayout(desktopTelaLayout);
        desktopTelaLayout.setHorizontalGroup(
            desktopTelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 657, Short.MAX_VALUE)
        );
        desktopTelaLayout.setVerticalGroup(
            desktopTelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 566, Short.MAX_VALUE)
        );

        btnDeletar.setText("Deletar");
        btnDeletar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeletarActionPerformed(evt);
            }
        });

        btnAlterarAluno.setText("Alterar");
        btnAlterarAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarAlunoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(desktopTela)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnNomeAluno)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnCadastrarAluno)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnListarAluno)
                        .addGap(18, 18, 18)
                        .addComponent(btnDeletar)
                        .addGap(18, 18, 18)
                        .addComponent(btnAlterarAluno)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnNomeAluno)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnCadastrarAluno)
                        .addComponent(btnListarAluno)
                        .addComponent(btnDeletar)
                        .addComponent(btnAlterarAluno)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(desktopTela)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnListarAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListarAlunoActionPerformed

        TelaTabelaAlunoTodos alunoTabela = new TelaTabelaAlunoTodos();
        
        this.desktopTela.add(alunoTabela);
        alunoTabela.setVisible(true);
        
    }//GEN-LAST:event_btnListarAlunoActionPerformed

    private void btnCadastrarAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarAlunoActionPerformed
        
        TelaCadastroAluno tela = new TelaCadastroAluno();
        
        this.desktopTela.add(tela);
        tela.setVisible(true);
        
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCadastrarAlunoActionPerformed

    private void btnNomeAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNomeAlunoActionPerformed
        
        TelaTabelaAlunoPesquisa tela = new TelaTabelaAlunoPesquisa();
        
        this.desktopTela.add(tela);
        tela.setVisible(true);
        
        // TODO add your handling code here:
    }//GEN-LAST:event_btnNomeAlunoActionPerformed

    private void btnDeletarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeletarActionPerformed

        TelaDeletarAluno tela = new TelaDeletarAluno();
        
        this.desktopTela.add(tela);
        tela.setVisible(true);

        // TODO add your handling code here:
    }//GEN-LAST:event_btnDeletarActionPerformed

    private void btnAlterarAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarAlunoActionPerformed

        TelaAlterarAluno tela = new TelaAlterarAluno();
        
        this.desktopTela.add(tela);
        tela.setVisible(true);

        // TODO add your handling code here:
    }//GEN-LAST:event_btnAlterarAlunoActionPerformed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
        TelaPrincipal tela = new TelaPrincipal();
        tela.setExtendedState(JFrame.MAXIMIZED_BOTH);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlterarAluno;
    private javax.swing.JButton btnCadastrarAluno;
    private javax.swing.JButton btnDeletar;
    private javax.swing.JButton btnListarAluno;
    private javax.swing.JButton btnNomeAluno;
    private javax.swing.JDesktopPane desktopTela;
    // End of variables declaration//GEN-END:variables
}
